version: "3.4"

services:

    db:
      # image: mysql:8.0
      image: 127.0.0.1:5000/banco
      build: "./"
      # container_name: bd-projeto-mysql
      environment:
        MYSQL_ROOT_PASSWORD: "projeto123"
        MYSQL_DATABASE: "crud_clientes"
      ports:
        - "3305:3306"

      volumes:
      - type: volume
        source: volume-banco
        target: /var/lib/mysql


      # deploy:
      #   placement:
      #     constraints: [node.role == manager]


      # volumes:
      #   - ./mysql-p:/var/lib/mysql
      networks:
        - backend

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        MYSQL_ROOT_PASSWORD: "projeto123"
      ports:
        - "8080:80"
      volumes:
        - ../data/php/admin/uploads4.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini

      networks:
        - backend
      
volumes:
  volume-banco:


networks: 
  backend:
#     driver: overlay      
#     # external: true




    

  